### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by hangukhiphop** [notjuliet/cleanfollow-bsky#1]
Error message: Invalid username or password

Troubleshooting steps taken:
new app password
deleted original app password
switched to extensionless browser so as to control for 3rd party conflicts

I have had success logging in multiple times in the past. To my recollection, I only started having this issue a couple weeks ago on mobile and assumed it might just be a mobile issue. However, every attempt listed above was on PC today.

**Comment by notjuliet** [comment]
If you're trying to login through OAuth you should not use an app password but your main one.
This method of authentication will eventually replace app passwords.
