### ISSUE TITLE
Idea: implement UI feedback when there's no accounts to show

### ISSUE THREAD

**Issue by garrucho** [notjuliet/cleanfollow-bsky#6]
hi there!

I was pretty sure the tool wasn't working for me, and it was driving me nuts on the why. happens that it simply had nothing to show for me in any of the five categories. 🤐 

I was really expecting _something_ to be there for a reason, but this _reason_ went away without me noticing, and the lack of feedback and some specific errors I saw at DevTools made me take it wrong.

about the errors, it seems that the API `app.bsky.actor.getProfile` fails frequently with an HTTP 401, returning this message:
```json
{
    "error": "use_dpop_nonce",
    "message": "Authorization server requires nonce in DPoP proof"
}
```

but that's not a big deal; it's just a matter of retrying.

**Comment by notjuliet** [comment]
i added a message when there is no account to unfollow
as for the error, i can reproduce it but i'm unsure why it's happening, it's very inconsistent, but might be due to oauth since it mentions DPoP
